let infoLibros = {
    'libros': [
      {
        id: "1",
        ISBN : "234-245-15-987-5",
        name: "Viaje al fin de la noche",
        author: "Louis-Ferdinand Céline",
        price: "45 dlls",
        editorial: "...",
        existence: "5",
      },
      {
        id: "2",
        ISBN : "234-245-15-987-5",
        name: "Las mil y una noches",
        author: "Anónimo",
        price: "30 dlls",
        editorial: "...",
        existence: "3",
      },
      {
        id: "3",
        ISBN : "234-245-15-987-5",
        name: "Saga de Njál",
        author: "Anónimo",
        price: "60 dlls",
        editorial: "...",
        existence: "8",
      },
      {
        id: "4",
        ISBN : "234-245-15-987-5",
        name: "Todo se desmorona",
        author: "Chinua Achebe",
        price: "80 dlls",
        editorial: "...",
        existence: "12",
      },
      {
        id: "5",
        ISBN : "234-245-15-987-5",
        name: "Cuentos infantiles",
        author: "Hans Christian Andersen",
        price: "60 dlls",
        editorial: "...",
        existence: "4",
      },
      {
        id: "6",
        ISBN : "234-245-15-987-5",
        name: "Todo se desmorona",
        author: "Chinua Achebe",
        price: "45 dlls",
        editorial: "...",
        existence: "20",
      },
      {
        id: "7",
        ISBN : "234-245-15-987-5",
        name: "Divina comedia",
        author: "Dante Alighieri",
        price: "95 dlls",
        editorial: "...",
        existence: "7",
      },
      {
        id: "8",
        ISBN : "234-245-15-987-5",
        name: "Orgullo y prejuicio",
        author: "Jane Austen",
        price: "25 dlls",
        editorial: "...",
        existence: "28",
      },
      {
        id: "9",
        ISBN : "234-245-15-987-5",
        name: "Papá Goriot",
        author: "Honoré de Balzac",
        price: "25 dlls",
        editorial: "...",
        existence: "45",
      },
      {
        id: "10",
        ISBN : "234-245-15-987-5",
        name: "Molloy, Malone muere, El Innombrable, una trilogía",
        author: "Samuel Beckett ",
        price: "85 dlls",
        editorial: "...",
        existence: "38",
      },
      {
        id: "11",
        ISBN : "234-245-15-987-5",
        name: "Decamerón",
        author: "Giovanni Boccaccio",
        price: "23 dlls",
        editorial: "...",
        existence: "26",
      },
      {
        id: "12",
        ISBN : "234-245-15-987-5",
        name: "Molloy, Malone muere, El Innombrable, una trilogía",
        author: "Samuel Beckett",
        price: "12 dlls",
        editorial: "...",
        existence: "20",
      },
      {
        id: "13",
        ISBN : "234-245-15-987-5",
        name: "Ficciones",
        author: "Jorge Luis Borges",
        price: "19 dlls",
        editorial: "...",
        existence: "20",
      },
      {
        id: "14",
        ISBN : "234-245-15-987-5",
        name: "Cumbres Borrascosas",
        author: "Emily Brontë",
        price: "18 dlls",
        editorial: "...",
        existence: "4",
      },
      {
        id: "15",
        ISBN : "234-245-15-987-5",
        name: "El extranjero",
        author: "Albert Camus",
        price: "57 dlls",
        editorial: "...",
        existence: "9",
      },
      {
        id: "16",
        ISBN : "234-245-15-987-5",
        name: "Don Quijote de la Mancha",
        author: "Miguel de Cervantes",
        price: "30 dlls",
        editorial: "...",
        existence: "10",
      },
      {
        id: "17",
        ISBN : "234-245-15-987-5",
        name: "Los cuentos de Canterbury",
        author: "Geoffrey Chaucer",
        price: "40 dlls",
        editorial: "...",
        existence: "18",
      },
      {
        id: "18",
        ISBN : "234-245-15-987-5",
        name: "Relatos cortos",
        author: "Antón Chéjov",
        price: "20 dlls",
        editorial: "...",
        existence: "13",
      },
      {
        id: "19",
        ISBN : "234-245-15-987-5",
        name: "Nostromo",
        author: "Joseph Conrad",
        price: "27 dlls",
        editorial: "...",
        existence: "13",
      },
      {
        id: "20",
        ISBN : "234-245-15-987-5",
        name: "Grandes Esperanzas",
        author: "Charles Dickens",
        price: "20 dlls",
        editorial: "...",
        existence: "13",
      },
      {
        id: "21",
        ISBN : "234-245-15-987-5",
        name: "Jacques el fatalista",
        author: "Denis Diderot",
        price: "20 dlls",
        editorial: "...",
        existence: "13",
      },
    ]
  };
  
  module.exports.infoLibros = infoLibros;
  